import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Award, Code2, Database, FileCode2, Github, Layers3, Server, ShieldCheck, X } from "lucide-react";
import type { Certification, Project } from "@/hooks/use-portfolio-data";

export function GithubActivity() {
  const [status, setStatus] = useState("Syncing public GitHub activity…");
  useEffect(() => { const control = new AbortController(); fetch("https://api.github.com/users/joashnyamai/events/public?per_page=1", { signal: control.signal }).then(response => response.ok ? response.json() : Promise.reject()).then((events: Array<{ repo?: { name?: string }; created_at?: string }>) => { const event = events[0]; if (!event?.repo?.name) return; const mins = event.created_at ? Math.max(1, Math.round((Date.now() - new Date(event.created_at).getTime()) / 60000)) : 0; setStatus(`${event.repo.name.replace("joashnyamai/", "")} · ${mins < 60 ? `${mins} min ago` : "recent activity"}`); }).catch(() => setStatus("Latest portfolio experiments")); return () => control.abort(); }, []);
  return <div className="os-github"><Github size={14}/><span>GitHub sync</span><b>{status}</b></div>;
}

export function XRay({ project, close }: { project: Project | null; close: () => void }) {
  const [node, setNode] = useState("Frontend");
  const layers = [{ name:"Frontend", icon:Layers3, text:"Responsive React components form the interface layer, with clear state boundaries and motion designed to explain change." }, { name:"API", icon:Server, text:"Service endpoints isolate business logic and give the interface a stable contract for reliable integrations." }, { name:"Database", icon:Database, text:"A relational data layer keeps workflow history consistent, indexed, and ready for reporting." }, { name:"Authentication", icon:ShieldCheck, text:"Role-aware access protects sensitive actions and keeps each user journey appropriately scoped." }];
  const current = layers.find(layer => layer.name === node) || layers[0];
  return <AnimatePresence>{project && <motion.div className="xray-layer" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={close}><motion.section className="xray-card" initial={{scale:.96,y:14}} animate={{scale:1,y:0}} exit={{scale:.96,y:14}} onMouseDown={event=>event.stopPropagation()}><header><div><span>PROJECT X-RAY</span><h2>{project.name}</h2></div><button onClick={close}><X size={18}/></button></header><p className="xray-summary">{project.summary}</p><div className="xray-flow">{layers.map((layer,index)=>{const Icon=layer.icon;return <div key={layer.name} className="flex items-center gap-2"><button onClick={()=>setNode(layer.name)} className={node===layer.name?"selected":""}><Icon size={14}/>{layer.name}</button>{index<layers.length-1&&<i>→</i>}</div>})}</div><section className="xray-detail"><current.icon size={20}/><div><b>{current.name}</b><p>{current.text}</p></div></section><footer>{project.stack.map(item=><span key={item}>{item}</span>)}</footer></motion.section></motion.div>}</AnimatePresence>;
}

export function Articles() { const posts=["Designing for low-bandwidth product realities","What QA taught me about durable interfaces","Building the first useful version, not the biggest one","A practical guide to API contract testing"]; return <div className="os-list-grid">{posts.map((post,index)=><article key={post}><span>ARTICLE / 0{index+1}</span><h3>{post}</h3><p>Technical notes from product work, shipping decisions, and quality engineering.</p><button>Read note →</button></article>)}</div>; }
export function Certificates({certifications}:{certifications:Certification[]}) { return <div className="os-list-grid">{certifications.map(cert=><article key={cert.name}><Award size={20}/><span>{cert.category}</span><h3>{cert.name}</h3><p>{cert.issuer}</p></article>)}</div>; }
export function CodeExplorer() { const [file,setFile]=useState("ProjectCard.tsx"); const snippets:Record<string,string>={"ProjectCard.tsx":"export function ProjectCard({ project }) {\n  return <article className=\"card\">\n    <h3>{project.name}</h3>\n    <Stack items={project.stack} />\n  </article>\n}","api-client.ts":"export async function getProjects() {\n  const response = await fetch('/api/projects');\n  if (!response.ok) throw new Error('Request failed');\n  return response.json();\n}","auth-flow.ts":"export function canAccess(user, permission) {\n  return user.permissions.includes(permission);\n}"}; return <div className="code-explorer"><aside>{Object.keys(snippets).map(name=><button key={name} onClick={()=>setFile(name)} className={file===name?"active":""}><FileCode2 size={14}/>{name}</button>)}</aside><section><div><span>COMPONENTS / {file}</span><b>Interactive code preview</b></div><pre>{snippets[file]}</pre><p><Code2 size={14}/> This is a focused example of the reusable pattern behind the portfolio’s product interface.</p></section></div>; }
export function Sandbox() { const [code,setCode]=useState("<button onclick=\"this.innerText='Nice — you ran it!'\">Run interaction</button>"); const [preview,setPreview]=useState(code); return <div className="sandbox"><div><label>HTML playground</label><textarea value={code} onChange={event=>setCode(event.target.value)}/><button onClick={()=>setPreview(code)}>Run preview</button></div><div><label>Live preview</label><iframe title="Sandbox preview" sandbox="allow-scripts" srcDoc={`<style>body{font:16px system-ui;background:#111827;color:#e5e7eb;padding:24px}button{background:#67e8f9;color:#082f49;border:0;border-radius:8px;padding:10px 14px;font-weight:700}</style>${preview}`}/></div></div>; }
